apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app

spec:
  replicas: 5
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app

    spec:
      containers:
        - name: flask-app-container
          image: sample-app
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
              protocol: TCP